#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

print("InnerG Intel Device Command Map")
print("=" * 36)
print()
print("iPhone       -> Command Deck: approvals, Telegram, capture, mobile QA")
print("MacBook 1    -> Build Studio: code, demos, deploys, creative production")
print("MacBook 2    -> Ops/Review: testing, dashboards, research, second checks")
print("GitHub       -> Source of Truth: repos, deploys, history")
print("Telegram     -> Command Bus: reports, updates, action prompts")
print("Codex        -> Agent Layer: build, verify, summarize, automate")
print()
print("Production stack coverage")
print("- Frontend")
print("- APIs & Backend Logic")
print("- Database & Storage")
print("- Auth & Permissions")
print("- Hosting & Deployment")
print("- Cloud & Compute")
print("- CI/CD & Version Control")
print("- Security & RLS")
print("- Rate Limiting")
print("- Caching & CDN")
print("- Load Balancing & Scaling")
print("- Error Tracking & Logs")
print("- Availability & Recovery")
print()
print(f"Docs: {ROOT / 'docs'}")
